version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: yoga
      POSTGRES_USER: yoga_user
      POSTGRES_PASSWORD: yoga_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./apps/api:/app
    command: ["air"] # Assuming you use air for hot reload in Go

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
    env_file:
      - .env
    depends_on:
      - api

volumes:
  pgdata:
